apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  selector:
    matchLabels:
      app: ekart
  replicas: 3
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: ekart
        image: manidevops2021/ekart:5.0
---
apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart
  ports:
  - port: 80
    protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ekart-service
# spec:
#   type: NodePort
#   selector:
#     app: ekart
#   ports:
#     - port: 80
#       protocol: TCP
#       nodePort: 30006

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: ekart-ingress
  namespace: ekart
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ekart-service
            port:
              number: 80
        path: /ekart
        pathType: Exact
status:
  loadBalancer: {}
