apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-argo-application
  namespace: argocd
spec:
  project: portfolio-project

  source:
    repoURL: https://github.com/mani-bca/k8s_argo_repo.git
    targetRevision: HEAD
    path: portfolio/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
